version: '3.7'

services:
  data_handler:
    image: dockerhub.fokus.fraunhofer.de:5000/5genesis/analytics/data_handler:0.2.6
    ports:
      - "5000:5000"
    secrets:
      - analytics_connections
  correlation:
    image: dockerhub.fokus.fraunhofer.de:5000/5genesis/analytics/correlation:0.1.4
    ports:
      - "5001:5001"
  prediction:
    image: dockerhub.fokus.fraunhofer.de:5000/5genesis/analytics/prediction:0.1.6
    ports:
      - "5002:5002"
  statistical_analysis:
    image: dockerhub.fokus.fraunhofer.de:5000/5genesis/analytics/statistical_analysis:0.1.3
    ports:
      - "5003:5003"
  feature_selection:
    image: dockerhub.fokus.fraunhofer.de:5000/5genesis/analytics/feature_selection:0.1.2
    ports:
      - "5004:5004"
  visualization:
    image: dockerhub.fokus.fraunhofer.de:5000/5genesis/analytics/visualization:1.0.0
    ports:
      - "5005:5005"
    secrets:
      - analytics_secret

secrets:
  analytics_connections:
    name: analytics_connections
    external: true
  analytics_secret:
    name: analytics_secret
    external: true
